"""
/***************************************************************************
 PlateauStatisticsVisualizationPluginDockWidget
                                 A QGIS plugin
 Urban Structure Assessment Dashboard
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-29
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Author
        email                : mail
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os

from qgis.PyQt import QtWidgets, uic # pylint: disable=import-error
from qgis.PyQt.QtCore import pyqtSignal # pylint: disable=import-error

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__),
    'PlateauStatisticsVisualizationPlugin_dockwidget_base.ui'
))


class PlateauStatisticsVisualizationPluginDockWidget(
    QtWidgets.QDockWidget, FORM_CLASS
):
    """
    QGISの「Plateau Statistics Visualization Plugin」で使用されるDockWidgetクラス。

    このDockWidgetは、プラグイン内のツールや操作を提供するメインのユーザーインターフェースコンポーネントです。
    QGISアプリケーション内で、フローティングまたはドッキング可能なパネルとして利用されます。

    属性:
        closingPlugin (pyqtSignal): DockWidgetが閉じられるときに発行されるシグナル。

    メソッド:
        __init__(parent=None):
            DockWidgetを初期化し、UIファイルで定義されたユーザーインターフェースをセットアップします。
        closeEvent(event):
            DockWidgetの閉じるイベントを処理し、`closingPlugin`シグナルを発行してからイベントを受け入れます。
    """
    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        super(
            PlateauStatisticsVisualizationPluginDockWidget, self
        ).__init__(parent)
        # Designer で作成されたユーザーインターフェースを設定します。
        # setupUI の後は、self.<オブジェクト名> で Designer で作成したオブジェクトにアクセスできます。
        # また、自動接続スロットを使用することもできます - 詳細は以下を参照してください:
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    def closeEvent(self, event):
        """
        DockWidgetの閉じるイベントを処理します。

        `closingPlugin`シグナルを発行してからイベントを受け入れます。

        :param event: 閉じるイベントオブジェクト。
        :type event: QCloseEvent
        """
        self.closingPlugin.emit()
        event.accept()
